name: Deploy Backend to EC2 via CodeDeploy

on:
  push:
    paths:
      - 'backend/**'
  workflow_dispatch:

env:
  PROJECT_NAME: websocket
  BUCKET_NAME: my-websocket
  CODE_DEPLOY_APP_NAME: WebSocketCodeDeploy
  DEPLOYMENT_GROUP_NAME: WebSocketCodeDeployGroup
  AWS_REGION: ap-northeast-2


jobs:
  build:
    # 실행 환경 설정
    runs-on: ubuntu-latest

    # 차례대로 실행
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x backend/gradlew
    
    # Gradle build (Test 제외)
    - name: Build with Gradle
      run: |
        cd backend
        ./gradlew clean build -x test
      
    # 압축 파일 만들기
    - name: Make Zip File
      run: |
        cd backend
        zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash
      
    # AWS 인증
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
      
    # S3 버킷으로 파일을 업로드
    - name: Upload to S3
      run: |
        cd backend
        aws s3 cp --region ${{ env.AWS_REGION }} ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

    # S3 버킷에 업로드 된 파일을 대상으로 CodeDeploy에서 배포 요청
    - name: Code Deploy
      run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
