name: React build

on:
  push:
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  BUCKET_NAME: my-websocket-client
  AWS_REGION: ap-northeast-2



jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout source code. # 레포지토리 체크아웃
        uses: actions/checkout@main

      # 2. AWS CLI 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. S3로 정적 파일 배포
      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend s3://${{ env.BUCKET_NAME }}/ \
            --region ${{ env.AWS_REGION }} \
            --delete
