name: React build

on:
  push:
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  BUCKET_NAME: my-websocket-client



jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout source code. # 레포지토리 체크아웃
        uses: actions/checkout@main

      - name: Deploy # S3에 배포하기
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./frontend s3://${{ env.BUCKET_NAME }}/ \
            --region ${{ env.AWS_REGION }} \
            --delete
